import Head from "next/head";
import Leftbar from "../src/components/Leftbar";
import Panel from "../src/components/Panel";
import Rightbar from "../src/components/Rightbar";
import Topbar from "../src/components/Topbar";
import { useArray } from "../src/Hooks/useArray";
import styles from "../styles/Home.module.css";

export default function Home() {
  const elements = useArray([]);

  return (
    <div className="h-screen flex flex-col">
      <Head>
        <title>Figma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Topbar />
      <div className="flex-1 flex justify-between">
        <Leftbar elements={elements} />
        <Panel elements={elements} />
        <Rightbar />
      </div>
    </div>
  );
}
